# Generated by Django 4.1 on 2022-08-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_scopes_alter_scope_main_article_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='article',
            field=models.ManyToManyField(related_name='scope', to='articles.article'),
        ),
        migrations.DeleteModel(
            name='Article_Scope',
        ),
    ]
