# Generated by Django 4.1 on 2022-08-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_scopes_tag_delete_scope_scopes_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scopes',
            options={'verbose_name': 'Cфера', 'verbose_name_plural': 'Cферы'},
        ),
    ]
